//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3G1_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        public int VendorID { get; set; }
        public string MaterialID { get; set; }
        public Nullable<decimal> SuppliesUnitPrice { get; set; }
    
        public virtual RawMaterial RawMaterial { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
